import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gerador IA',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Toaster 
          position="top-right"
          gutter={10}
          toastOptions={{  
            success: {
              style: {
                background: "#1e293b",
                color: "#fff"
              }
            },
            error: {
              style: {
                background: "#1e293b",
                color: "#fff"
              }
            }
          }}
        />
        <main className="bg-slate-950 w-screen min-h-screen flex items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  )
}
